[package]
name = "basic_os"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9"

[[bin]]
name = "basic_os"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
